// Golden test for the hand-ported Park-and-Ride function (the "complex path").
// pnr_golden.json is generated by scripts/generate_pnr_golden.py from the
// authoritative Python engine; the TS port must reproduce every per-TAZ value.

import { describe, it, expect } from "vitest";
import golden from "./__fixtures__/pnr_golden.json";
import { parkAndRide, type ParkAndRideArgs } from "./parkAndRide";
import type { TazInputs } from "./types";

interface PnrExpected {
  taz_id: string;
  pct_vmt_reduction: number;
  base_vmt: number;
  daily_vmt_reduction: number;
}
interface PnrScenario {
  label: string;
  taz_inputs: Record<string, number | string | null>[];
  args: ParkAndRideArgs;
  expected: PnrExpected[];
}

describe("park-and-ride port: golden-value tests vs the Python engine", () => {
  for (const sc of golden as unknown as PnrScenario[]) {
    describe(sc.label, () => {
      const tazs = sc.taz_inputs.map((t) => t as unknown as TazInputs);
      const rows = parkAndRide(tazs, sc.args);
      const byId = new Map(rows.map((r) => [r.taz_id, r]));

      for (const exp of sc.expected) {
        it(`TAZ ${exp.taz_id}`, () => {
          const got = byId.get(exp.taz_id);
          expect(got, `no result row for TAZ ${exp.taz_id}`).toBeDefined();
          expect(got!.pct_vmt_reduction).toBeCloseTo(exp.pct_vmt_reduction, 10);
          expect(got!.base_vmt).toBeCloseTo(exp.base_vmt, 6);
          expect(got!.daily_vmt_reduction).toBeCloseTo(exp.daily_vmt_reduction, 4);
          expect(got!.base_vmt_purpose).toBe("commute");
        });
      }
    });
  }
});
