"""
publish_enriched_taz.py — publish the prepared per-TAZ enriched table as a
hosted feature layer (and a containing web map) on ArcGIS Online.

This wraps prepare_taz() so the published service carries every column the
strategy_calculations.py functions read: stocks, activity, area_type,
per-facility lane-miles, transit metrics, ACS mode share, NOAA bikeable days,
PACE / state-highway / urban-area attributes.

Usage:
    python scripts/publish_enriched_taz.py [--env {staging,prod}] [--overwrite] [--dry-run]

Reads username/password interactively. The target org/portal and the existing
item IDs come from scripts/agol_items.json (selected by --env); --agol-url
overrides. Reads/writes that config so the first CREATE run self-populates the
item IDs a later --overwrite refresh needs. Set $AGOL_URL to override the org.
"""
from __future__ import annotations

import argparse
import getpass
import json
import os
import re
import sys
import tempfile
import warnings
from pathlib import Path

import geopandas as gpd
import pandas as pd
import shapely

# arcgis 2.4.x's own Pydantic models still use the deprecated v1-style
# `class Config` (e.g. arcgis/graph/response_types.py), which spams
# PydanticDeprecatedSince20 on import. That's third-party library code we can't
# change, so silence just that category for clean publish output.
try:
    from pydantic.warnings import PydanticDeprecatedSince20
    warnings.filterwarnings("ignore", category=PydanticDeprecatedSince20)
except Exception:
    warnings.filterwarnings("ignore", category=DeprecationWarning, module=r"arcgis(\.|$)")

sys.path.insert(0, str(Path(__file__).resolve().parent))
from paths import DATA_DIR, OUTPUTS_DIR
from prepare_taz import (
    DEFAULT_TAZ_PATH,
    PROJ_CRS,
    load_taz,
    prepare_taz,
)

DEFAULT_AGOL_URL = os.environ.get("AGOL_URL", "https://hspartner.maps.arcgis.com")
DEFAULT_FOLDER = "CDOT TDM Calculator"
# Persisted prod/staging AGOL identifiers (single source of truth; see the file's
# own _comment). The publish script reads it to resolve the target org + the
# existing FL item for --overwrite, and writes new IDs back after a create.
AGOL_ITEMS_PATH = Path(__file__).resolve().parent / "agol_items.json"
# The app's data contract: the exact attribute columns queryTaz.ts reads. The
# schema-validation gate parses this list at runtime (source of truth below).
QUERY_TAZ_TS_PATH = (
    Path(__file__).resolve().parent.parent / "app" / "src" / "data" / "queryTaz.ts"
)
# Topology-preserving simplification tolerance (meters) for the published
# *display* geometry. ~25 m leaves ~23% of TAZ vertices (~77% cut) with no
# perceptible change at selection zoom (per measured data on the 2019 layer).
# Attributes are unaffected — area/density were computed from full-resolution
# geometry in prepare_taz(). Pass --simplify-tolerance 0 for full resolution.
DEFAULT_SIMPLIFY_TOLERANCE_M = 25.0

LAYER_TITLE = "CDOT TDM Calculator - TAZ Enriched"
LAYER_SNIPPET = (
    "Per-TAZ enriched table for the CDOT TDM Calculator. Joins CDOT 2019 SWTDM "
    "TAZ geometry with derived activity, network, transit, ACS mode share, and "
    "NOAA bikeable-days attributes used by the strategy formulas."
)
LAYER_DESCRIPTION = (
    "Per-zone enriched dataset built from CDOT 2019 Statewide Travel Demand Model "
    "outputs plus background sources (ACS B08301, NOAA NCEI 1991-2020 daily "
    "normals, CDOT public highway/PACE/transit feature services). Generated by "
    "scripts/prepare_taz.py. One row per TAZ. Used as the data source for the "
    "CDOT TDM Calculator web application."
)
WEBMAP_TITLE = "CDOT TDM Calculator"
WEBMAP_SNIPPET = (
    "Map used by the CDOT TDM Calculator web application. Shows the enriched TAZ "
    "layer for project-area selection."
)
WEBMAP_DESCRIPTION = (
    "Web map consumed by the CDOT TDM Calculator. Bundles the enriched TAZ "
    "feature layer over a neutral gray-canvas basemap so users can pick TAZs "
    "for analysis."
)
COMMON_TAGS = ["CDOT", "TDM", "TDM Calculator", "Colorado", "TAZ", "VMT"]
COMMON_LICENSE = (
    "Sources: CDOT 2019 Statewide Travel Demand Model; U.S. Census Bureau ACS "
    "5-Year (B08301); NOAA NCEI 1991-2020 daily climate normals; CDOT public "
    "highway, PACE, urban-areas, and transit feature services."
)


def load_agol_items(path: Path = AGOL_ITEMS_PATH) -> dict:
    """Load the committed AGOL identifiers config (prod/staging item IDs + URLs)."""
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


def save_agol_items(config: dict, path: Path = AGOL_ITEMS_PATH) -> None:
    """Write the AGOL identifiers config back, preserving 2-space indentation."""
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(config, fh, indent=2)
        fh.write("\n")
    print(f"  Updated AGOL items config: {path}")


def parse_contract_fields(path: Path = QUERY_TAZ_TS_PATH) -> list[str]:
    """Parse the app's TAZ_FIELDS data contract out of queryTaz.ts at runtime.

    queryTaz.ts is the authoritative source of truth for the attribute columns
    the app reads. Parsing it (rather than hardcoding) keeps the publish gate in
    lockstep with the app — a field added there is enforced here automatically.
    """
    text = path.read_text(encoding="utf-8")
    m = re.search(r"const\s+TAZ_FIELDS\s*=\s*\[(.*?)\]", text, re.DOTALL)
    if not m:
        raise RuntimeError(
            f"Could not locate the TAZ_FIELDS array in {path}; the schema-"
            f"validation gate can't determine the data contract."
        )
    fields = re.findall(r"""["']([^"']+)["']""", m.group(1))
    if not fields:
        raise RuntimeError(f"TAZ_FIELDS array in {path} parsed to zero fields.")
    return fields


def validate_contract(
    gdf: gpd.GeoDataFrame,
    contract_fields: list[str] | None = None,
    coverage_threshold: float = 0.50,
) -> None:
    """Schema-validation gate: assert the gdf satisfies the app's TAZ_FIELDS contract.

    Validate at the stage where the short snake_case contract names are present
    (i.e. before/independent of sanitize_columns — those names are already
    AGOL-safe so sanitize leaves them unchanged). Behavior:
      * FAIL LOUDLY (raise) listing any MISSING contract field.
      * WARN (don't fail) for any present field whose non-null coverage is below
        ``coverage_threshold`` (default 50%).
    """
    if contract_fields is None:
        contract_fields = parse_contract_fields()
    print(f"Validating schema against {len(contract_fields)} contract fields "
          f"(from {QUERY_TAZ_TS_PATH.name}) ...")

    present = set(gdf.columns)
    missing = [f for f in contract_fields if f not in present]
    if missing:
        raise RuntimeError(
            "Schema-validation gate FAILED: the assembled table is missing "
            f"{len(missing)} field(s) the app contract (TAZ_FIELDS) requires: "
            f"{missing}. Fix prepare_taz.py (or the source->contract field map) "
            f"before publishing."
        )

    n = len(gdf) or 1
    low_coverage: list[tuple[str, float]] = []
    for field in contract_fields:
        non_null = int(gdf[field].notna().sum())
        coverage = non_null / n
        if coverage < coverage_threshold:
            low_coverage.append((field, coverage))
    if low_coverage:
        print(f"  WARNING: {len(low_coverage)} contract field(s) below "
              f"{coverage_threshold:.0%} non-null coverage (not fatal):")
        for field, coverage in low_coverage:
            print(f"    {field}: {coverage:.0%} non-null")
    print(f"  Schema OK: all {len(contract_fields)} contract fields present.")


_VALID = re.compile(r"[^A-Za-z0-9_]+")


def sanitize_columns(gdf: gpd.GeoDataFrame, max_len: int = 60) -> tuple[gpd.GeoDataFrame, dict[str, str]]:
    """Rename columns to be AGOL-safe; return renamed gdf + original->clean mapping."""
    mapping: dict[str, str] = {}
    seen: set[str] = set()
    for col in gdf.columns:
        if col == "geometry":
            mapping[col] = col
            continue
        clean = _VALID.sub("_", str(col)).strip("_")
        if not clean:
            clean = "field"
        if clean[0].isdigit():
            clean = "f_" + clean
        clean = clean[:max_len]
        base, n = clean, 1
        while clean.lower() in seen:
            suffix = f"_{n}"
            clean = base[: max_len - len(suffix)] + suffix
            n += 1
        seen.add(clean.lower())
        mapping[col] = clean
    return gdf.rename(columns=mapping), mapping


def generalize_coverage(gdf: gpd.GeoDataFrame, tolerance_m: float) -> gpd.GeoDataFrame:
    """Topology-preserving simplification of the TAZ polygon coverage.

    Uses GEOS coverage simplification (via shapely) so shared borders between
    adjacent TAZs stay coincident — no slivers or gaps, unlike a per-polygon
    ``simplify``. Runs in a projected CRS so ``tolerance_m`` is in meters, then
    returns geometry in the input CRS. Display-only: attributes were already
    computed from full-resolution geometry upstream.
    """
    if not tolerance_m or tolerance_m <= 0:
        return gdf
    src_crs = gdf.crs
    proj = gdf.to_crs(PROJ_CRS)
    geoms = proj.geometry.to_numpy()
    # A handful of CDOT TAZ rings are invalid; buffer(0) repairs them to valid
    # Polygon/MultiPolygon (coverage_simplify rejects other geometry types).
    invalid = ~shapely.is_valid(geoms)
    if invalid.any():
        geoms[invalid] = shapely.buffer(geoms[invalid], 0)
    before = int(shapely.get_num_coordinates(geoms).sum())
    simplified = shapely.coverage_simplify(geoms, tolerance_m, simplify_boundary=True)
    after = int(shapely.get_num_coordinates(simplified).sum())
    print(f"  Generalized geometry @ {tolerance_m:g} m: "
          f"{before:,} -> {after:,} vertices ({100 * after / before:.0f}%)")
    proj = proj.set_geometry(gpd.GeoSeries(simplified, crs=PROJ_CRS, index=proj.index))
    return proj.to_crs(src_crs)


def build_enriched_gdf(
    simplify_tolerance_m: float = DEFAULT_SIMPLIFY_TOLERANCE_M,
) -> tuple[gpd.GeoDataFrame, dict[str, str]]:
    """Run prepare_taz, attach (generalized) TAZ polygon geometry, return a sanitized GeoDataFrame."""
    print("Running prepare_taz() ...")
    prep = prepare_taz()
    df = prep.df.copy()
    quality = prep.quality.copy()
    print(f"  Prepared table: {len(df):,} rows x {df.shape[1]} cols")

    # Merge in the quality flags so consumers can pre-filter on data coverage.
    df = df.merge(quality, on="taz_id", how="left", suffixes=("", "_q"))
    print(f"  After quality join: {df.shape[1]} cols")

    # Bring in the TAZ polygon geometry (WGS84) keyed on TAZ_new_ID.
    print("Loading TAZ geometry (WGS84) ...")
    taz_geo = load_taz(DEFAULT_TAZ_PATH, crs="EPSG:4326")
    taz_geo["taz_id"] = taz_geo["TAZ_new_ID"].astype("Int64").astype(str)
    geo_only = taz_geo[["taz_id", "geometry"]]
    geo_only = generalize_coverage(geo_only, simplify_tolerance_m)

    merged = geo_only.merge(df, on="taz_id", how="inner")
    gdf = gpd.GeoDataFrame(merged, geometry="geometry", crs="EPSG:4326")
    print(f"  Joined geometry: {len(gdf):,} polygons")

    # Schema-validation gate (before sanitize, while the short snake_case
    # contract names are present). Fails loudly if a TAZ_FIELDS column is
    # missing; warns on low-coverage fields.
    validate_contract(gdf)

    # Coerce object/string columns AGOL can't infer (avoids 0-length type errors).
    for col in gdf.columns:
        if col == "geometry":
            continue
        if gdf[col].dtype == "object":
            gdf[col] = gdf[col].astype(str).where(gdf[col].notna(), None)

    # Cast pandas nullable Int64 -> float64 (AGOL python API doesn't accept Int64).
    for col in gdf.columns:
        if col == "geometry":
            continue
        if str(gdf[col].dtype) == "Int64":
            gdf[col] = gdf[col].astype("float64")

    sanitized, field_map = sanitize_columns(gdf)
    renamed = {k: v for k, v in field_map.items() if k != v}
    if renamed:
        print(f"  Renamed {len(renamed)} column(s) for AGOL compatibility")
        for orig, clean in list(renamed.items())[:8]:
            print(f"    {orig!r} -> {clean!r}")
        if len(renamed) > 8:
            print(f"    ... ({len(renamed) - 8} more)")

    return sanitized, field_map


def write_field_map(field_map: dict[str, str], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    pd.DataFrame(field_map.items(), columns=["original", "arcgis"]).to_csv(path, index=False)
    print(f"  Field map written: {path}")


def connect_gis(agol_url: str):
    """Sign in to AGOL/Portal. Uses AGOL_USER / AGOL_PASSWORD from the environment
    (e.g. loaded from .env) when present for non-interactive runs; otherwise
    prompts. Returns the connected GIS object."""
    from arcgis.gis import GIS

    user = os.environ.get("AGOL_USER")
    pw = os.environ.get("AGOL_PASSWORD")
    if user and pw:
        print(f"Connecting to {agol_url} as {user} (credentials from environment) ...")
    else:
        user = input(f"AGOL username for {agol_url}: ").strip()
        pw = getpass.getpass("AGOL password: ")
        print(f"Connecting to {agol_url} ...")
    gis = GIS(agol_url, user, pw)
    print(f"  Signed in as: {gis.users.me.username} ({gis.users.me.role})")
    return gis


def write_geojson(gdf: gpd.GeoDataFrame, td: str, filename: str = "taz_enriched.geojson") -> Path:
    """Serialize the gdf to a GeoJSON file in ``td`` and report its size."""
    geojson_path = Path(td) / filename
    print(f"  Writing GeoJSON to {geojson_path} ...")
    gdf.to_file(geojson_path, driver="GeoJSON")
    size_mb = geojson_path.stat().st_size / 1e6
    print(f"  GeoJSON size: {size_mb:.1f} MB")
    return geojson_path


def overwrite_feature_layer(gdf: gpd.GeoDataFrame, agol_url: str, fl_item_id: str) -> str:
    """Overwrite the EXISTING hosted feature layer in place, keeping its item ID
    and service URL stable (so the app needs no redeploy on a data refresh).

    Uses FeatureLayerCollection.manager.overwrite(); overwrite() requires the
    same schema as the original publish. Returns the (unchanged) item ID.
    """
    from arcgis.features import FeatureLayerCollection
    from arcgis.features import GeoAccessor, GeoSeriesAccessor  # noqa: F401  (registers .spatial accessor)

    gis = connect_gis(agol_url)

    item = gis.content.get(fl_item_id)
    if item is None:
        raise RuntimeError(
            f"--overwrite target feature layer item '{fl_item_id}' not found in "
            f"{agol_url}. Check agol_items.json or run an initial create publish."
        )
    print(f"Overwriting feature layer in place: '{item.title}' ({item.id})")

    with tempfile.TemporaryDirectory() as td:
        geojson_path = write_geojson(gdf, td)
        print("  Overwriting hosted feature layer data ...")
        flc = FeatureLayerCollection.fromitem(item)
        flc.manager.overwrite(str(geojson_path))

    print(f"  Overwrite complete. Item ID + service URL unchanged: {item.id}")
    print(f"  Service URL: {item.url}")
    return item.id


def publish(gdf: gpd.GeoDataFrame, agol_url: str, folder: str, share: str,
            title_suffix: str = "") -> tuple[str, str, str]:
    """Publish the enriched layer + a containing web map.

    ``title_suffix`` is appended to the layer + web-map titles (e.g. a publish
    date) so a new dated set can be created without colliding with / deleting an
    existing one.

    Returns (layer_item_id, webmap_item_id, feature_layer_url).
    """
    import json as _json
    import uuid

    from arcgis.features import GeoAccessor, GeoSeriesAccessor  # noqa: F401  (registers .spatial accessor)
    from arcgis.gis import ItemProperties, SharingLevel

    layer_title = LAYER_TITLE + title_suffix
    webmap_title = WEBMAP_TITLE + title_suffix

    share_level = {
        "private": SharingLevel.PRIVATE,
        "org": SharingLevel.ORG,
        "public": SharingLevel.EVERYONE,
    }[share]

    gis = connect_gis(agol_url)

    # Ensure the folder exists and get a Folder handle to add items to (arcgis
    # 2.3+ API; gis.content.add(folder=...) is deprecated, removed in 3.0).
    print(f"  Ensuring folder exists: {folder}")
    folder_obj = gis.content.folders.create(folder, exist_ok=True)

    # Refuse to overwrite an existing item with the same title.
    owner = gis.users.me.username
    existing = gis.content.search(
        query=f'title:"{layer_title}" AND owner:{owner}',
        item_type="Feature Layer",
    )
    if existing:
        raise RuntimeError(
            f"A feature layer titled '{layer_title}' already exists "
            f"({existing[0].id}). Delete it from My Content or use a different --title-suffix."
        )

    print(f"Publishing feature layer '{layer_title}' ({len(gdf):,} features, "
          f"{gdf.shape[1]-1} attribute columns) ...")
    # arcgis 2.x's sedf.to_featurelayer() round-trips through pyshp -> shapefile,
    # which caps field names at 10 chars. To preserve the long, descriptive
    # columns prepare_taz produces (length_weighted_auto_op_cost_pk, etc.) we
    # upload the GeoDataFrame as a GeoJSON file and publish that — GeoJSON has
    # no field-name length limit.
    with tempfile.TemporaryDirectory() as td:
        # AGOL dedupes uploaded files by filename within a user's content, so a
        # create must use a unique source filename (the title can repeat but the
        # file can't). Derive it from the title suffix.
        safe = re.sub(r"[^A-Za-z0-9]+", "_", title_suffix).strip("_")
        gj_name = f"taz_enriched_{safe}.geojson" if safe else "taz_enriched.geojson"
        geojson_path = write_geojson(gdf, td, gj_name)

        print("  Uploading GeoJSON to AGOL ...")
        gj_item = folder_obj.add(
            item_properties=ItemProperties(
                item_type="GeoJson",
                title=layer_title + " (source)",
                tags=COMMON_TAGS,
                snippet=LAYER_SNIPPET + " (source GeoJSON; the published hosted layer is the canonical artifact).",
            ),
            file=str(geojson_path),
        ).result()
        print(f"    Source item: {gj_item.id}")

        print("  Publishing to hosted feature layer ...")
        fl_item = gj_item.publish(file_type="geojson")
        print(f"  Created: {fl_item.id}  ({fl_item.homepage})")

        # Rename the published service to the canonical title (publish() picks
        # up the source GeoJSON's title verbatim).
        fl_item.update(item_properties={"title": layer_title})

    fl_item.update(item_properties={
        "snippet":           LAYER_SNIPPET,
        "description":       LAYER_DESCRIPTION,
        "licenseInfo":       COMMON_LICENSE,
        "accessInformation": "Colorado Department of Transportation; U.S. Census; NOAA NCEI.",
    })

    fl_item.sharing.sharing_level = share_level
    gj_item.sharing.sharing_level = share_level
    print(f"  Shared: {share}")

    # arcgis 2.x removed the WebMap helper class, so we author the web-map JSON
    # directly and add it as a content item. The JSON below targets schema 2.31
    # (current AGOL classic-map-viewer schema as of 2026).
    fl_service_url = fl_item.url + "/0"
    # AGOL "Light Gray Canvas" reference (no-attribution-pain neutral basemap).
    # Item id is the well-known Esri-owned Light Gray Canvas Base vector tile layer.
    GRAY_VECTOR_BASE_ITEM = "291da5eab3a0412593b66d384379f89f"
    GRAY_VECTOR_REF_ITEM  = "1768e8369a214dfab4e2167d5c5f2454"

    webmap_json = {
        "version": "2.31",
        "operationalLayers": [
            {
                "id": uuid.uuid4().hex,
                "title": layer_title,
                "url": fl_service_url,
                "itemId": fl_item.id,
                "layerType": "ArcGISFeatureLayer",
                "opacity": 0.85,
                "visibility": True,
                "popupInfo": {
                    "title": "TAZ {taz_id}",
                    "fieldInfos": [
                        {"fieldName": "taz_id",     "label": "TAZ ID",     "visible": True},
                        {"fieldName": "county",     "label": "County",     "visible": True},
                        {"fieldName": "mpo",        "label": "MPO/TPR",    "visible": True},
                        {"fieldName": "area_type",  "label": "Area type",  "visible": True},
                        {"fieldName": "population", "label": "Population", "visible": True,
                         "format": {"places": 0, "digitSeparator": True}},
                        {"fieldName": "employment", "label": "Employment", "visible": True,
                         "format": {"places": 0, "digitSeparator": True}},
                        {"fieldName": "daily_vmt",  "label": "Daily VMT",  "visible": True,
                         "format": {"places": 0, "digitSeparator": True}},
                    ],
                },
            }
        ],
        "baseMap": {
            "title": "Light Gray Canvas",
            "baseMapLayers": [
                {
                    "id": "gray-vector-base",
                    "title": "Light Gray Canvas Base",
                    "layerType": "VectorTileLayer",
                    "styleUrl": (f"https://cdn.arcgis.com/sharing/rest/content/items/"
                                 f"{GRAY_VECTOR_BASE_ITEM}/resources/styles/root.json"),
                    "itemId": GRAY_VECTOR_BASE_ITEM,
                },
                {
                    "id": "gray-vector-reference",
                    "title": "Light Gray Canvas Reference",
                    "layerType": "VectorTileLayer",
                    "isReference": True,
                    "styleUrl": (f"https://cdn.arcgis.com/sharing/rest/content/items/"
                                 f"{GRAY_VECTOR_REF_ITEM}/resources/styles/root.json"),
                    "itemId": GRAY_VECTOR_REF_ITEM,
                },
            ],
        },
        "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        "initialState": {
            "viewpoint": {
                "targetGeometry": {
                    "xmin": -12141000, "ymin": 4430000,
                    "xmax": -11360000, "ymax": 5040000,
                    "spatialReference": {"wkid": 102100, "latestWkid": 3857},
                }
            }
        },
        "authoringApp": "CDOT TDM Calculator publish script",
        "authoringAppVersion": "1.0",
    }

    existing_wm = gis.content.search(
        query=f'title:"{webmap_title}" AND owner:{owner}',
        item_type="Web Map",
    )
    if existing_wm:
        raise RuntimeError(
            f"A web map titled '{webmap_title}' already exists "
            f"({existing_wm[0].id}). Delete it or use a different --title-suffix."
        )

    print(f"Saving web map '{webmap_title}' ...")
    wm_item = folder_obj.add(
        item_properties=ItemProperties(
            item_type="Web Map",
            title=webmap_title,
            snippet=WEBMAP_SNIPPET,
            description=WEBMAP_DESCRIPTION,
            tags=COMMON_TAGS,
            type_keywords=["Web Map", "Map", "Online Map", "Collector"],
        ),
        text=_json.dumps(webmap_json),
    ).result()
    print(f"  Created: {wm_item.id}  ({wm_item.homepage})")
    wm_item.sharing.sharing_level = share_level
    print(f"  Shared: {share}")

    return fl_item.id, wm_item.id, fl_service_url


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--env", default="prod",
                    help="Which agol_items.json entry to target (default: prod). Any key "
                         "present in agol_items.json is accepted, e.g. a dated key for a "
                         "one-off create that must not clobber the prod entry.")
    ap.add_argument("--overwrite", action="store_true",
                    help="Overwrite the EXISTING hosted feature layer named in "
                         "agol_items.json[env] in place (stable item ID + URL; "
                         "no app redeploy), instead of creating new items.")
    ap.add_argument("--dry-run", action="store_true",
                    help="Build the enriched gdf and write the field map; skip the AGOL publish.")
    ap.add_argument("--agol-url", default=None,
                    help="AGOL/Portal org URL override. Resolution order: this "
                         "flag -> agol_items.json[env].portal_url -> $AGOL_URL -> "
                         f"default ({DEFAULT_AGOL_URL}).")
    ap.add_argument("--folder", default=DEFAULT_FOLDER,
                    help=f"AGOL content folder (default: '{DEFAULT_FOLDER}')")
    ap.add_argument("--share", choices=("private", "org", "public"), default="org",
                    help="Sharing scope for the new items (default: org)")
    ap.add_argument("--title-suffix", default="",
                    help="Appended to the layer + web-map titles (e.g. ' 2026-06-29') so a "
                         "dated set can be created without colliding with an existing one.")
    ap.add_argument("--simplify-tolerance", type=float, default=DEFAULT_SIMPLIFY_TOLERANCE_M,
                    help=f"Coverage simplify tolerance in meters for the published display "
                         f"geometry (default: {DEFAULT_SIMPLIFY_TOLERANCE_M:g}; 0 = full resolution)")
    args = ap.parse_args()

    # Load the persisted identifiers and select the env entry.
    config = load_agol_items()
    env_cfg = config.get(args.env)
    if env_cfg is None:
        print(f"ERROR: '{args.env}' is not an entry in {AGOL_ITEMS_PATH}.", file=sys.stderr)
        return 2

    # Resolve target org URL: --agol-url -> config[env].portal_url -> $AGOL_URL -> default.
    agol_url = args.agol_url or env_cfg.get("portal_url") or DEFAULT_AGOL_URL
    print(f"Target env: {args.env}  |  org: {agol_url}  |  "
          f"mode: {'overwrite-in-place' if args.overwrite else 'create'}")

    # Fail early (before the ~5-min enrichment) if --overwrite has no target.
    if args.overwrite and not args.dry_run and not env_cfg.get("feature_layer_item_id"):
        print(
            f"ERROR: --overwrite needs an existing feature_layer_item_id in "
            f"{AGOL_ITEMS_PATH}['{args.env}'], but it is empty. Run an initial "
            f"create publish first (omit --overwrite); it will self-populate the "
            f"item IDs so subsequent runs can --overwrite.",
            file=sys.stderr,
        )
        return 2

    gdf, field_map = build_enriched_gdf(args.simplify_tolerance)
    write_field_map(
        field_map,
        DATA_DIR / "_field_maps" / "CDOT_TDM_Calculator_TAZ_Enriched_fields.csv",
    )

    if args.dry_run:
        print("\n[dry-run] Skipping AGOL publish.")
        out_path = OUTPUTS_DIR / "taz_enriched.geojson"
        out_path.parent.mkdir(parents=True, exist_ok=True)
        gdf.to_file(out_path, driver="GeoJSON")
        print(f"[dry-run] Wrote local GeoJSON: {out_path} ({out_path.stat().st_size/1e6:.1f} MB)")
        return 0

    if args.overwrite:
        fl_id = overwrite_feature_layer(gdf, agol_url, env_cfg["feature_layer_item_id"])
        print()
        print("=" * 60)
        print("Done (overwrite-in-place).")
        print(f"  Feature layer item id: {fl_id}  (unchanged)")
        print(f"  Web map item id:       {env_cfg.get('web_map_item_id') or '(unchanged)'}")
        print("=" * 60)
        return 0

    fl_id, wm_id, fl_url = publish(gdf, agol_url, args.folder, args.share, args.title_suffix)

    # Self-populate the config so a later --overwrite refresh has its target.
    env_cfg["portal_url"] = agol_url
    env_cfg["feature_layer_item_id"] = fl_id
    env_cfg["feature_layer_url"] = fl_url
    env_cfg["web_map_item_id"] = wm_id
    save_agol_items(config)

    print()
    print("=" * 60)
    print("Done (create).")
    print(f"  Feature layer item id: {fl_id}")
    print(f"  Feature layer URL:     {fl_url}")
    print(f"  Web map item id:       {wm_id}")
    print(f"  Wrote IDs to {AGOL_ITEMS_PATH} ['{args.env}'] for future --overwrite runs.")
    print("=" * 60)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
