// Copy the compiled strategy catalog into the app so it can be imported as a
// typed module (no runtime fetch). Runs automatically before dev/build/test
// via the pre* npm scripts. Keeps the catalog repo and the app build decoupled.
//
// Source of truth: strategy-catalog/compiled/strategies.json (generated by
// strategy-catalog/build.py from the per-strategy YAML). Edit the YAML, run
// build.py, then this script picks up the result.

import { cpSync, copyFileSync, existsSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const src = resolve(here, "../../strategy-catalog/compiled/strategies.json");
const dst = resolve(here, "../src/strategies/catalog.json");
const imgSrc = resolve(here, "../../strategy-catalog/images");
const imgDst = resolve(here, "../public/catalog-images");

if (!existsSync(src)) {
  // The sibling catalog folder isn't present (e.g. a CI checkout of just the
  // app). The committed catalog.json is used as-is — don't fail the build.
  if (existsSync(dst)) {
    console.log(`sync:catalog — source not found, using committed ${dst}`);
    process.exit(0);
  }
  console.error(`sync:catalog — source not found and no committed catalog.json: ${src}`);
  process.exit(1);
}

mkdirSync(dirname(dst), { recursive: true });
copyFileSync(src, dst);
console.log(`sync:catalog — synced ${src} → ${dst}`);

// Mirror the catalog's images into the app's public dir so the paths
// referenced by strategies/categories (catalog-images/<file>) resolve.
// No-op beyond the .gitkeep until illustrative art is added to the catalog.
if (existsSync(imgSrc)) {
  cpSync(imgSrc, imgDst, { recursive: true });
  console.log(`sync:catalog — mirrored images → ${imgDst}`);
}
